In [2]:
import numpy as np
import scipy.sparse as sparse
import random
import hashlib

# Load in Data

In [3]:
data = np.load('Data/user_movie_rating.npy')[:,0:2]

In [66]:
col = data[:, 0]
row = data[:, 1]

n_col = col.max() + 1
n_row = row.max() + 1 

M = sparse.coo_matrix((np.ones(len(data)), (row, col)), shape=(n_row, n_col)).tocsr()
small_M  = M[:,0:100]

In [67]:
perm = 100 
perm_seeds = []
row_len,_ = small_M.get_shape()
seed = 100000
for i in range(perm):
    perm_seeds.append(int(hashlib.sha256(str(seed+i).encode()).hexdigest(),16)%4294967295)


In [69]:

matrix = M

nrows = matrix.shape[0]
index = np.arange(nrows)
signature = []
for seed in perm_seeds:
    row_signature = []
    random.seed(seed)
    index_perm = index
    np.random.shuffle(index_perm)
    perm_M = matrix[index_perm,1:] #0 index is empty
    row_signature = np.full(perm_M.shape[1], np.inf, dtype=int)
    row_idx = 0
    #TODO: works quite well but the indexes change as soon as i remove the ones already found; perhaps a tracking list??
    while perm_M.shape[1] != 0:
        matches = perm_M[row_idx,:].nonzero()[1]
        non_matches = np.setdiff1d(np.arange(perm_M.shape[1]), matches)
        row_signature[matches] = row_idx
        perm_M = perm_M[:,non_matches]
        row_idx +=1
    signature.append(row_signature)
        

        


c:\Users\jaspe\AppData\Local\Programs\Python\Python313\Lib\site-packages\numpy\_core\numeric.py:387: RuntimeWarning: invalid value encountered in cast
  multiarray.copyto(a, fill_value, casting='unsafe')


In [70]:
nrows

17771

In [62]:
M.shape

(17771, 103704)

In [58]:
ncols

103704

In [43]:
np.array(signature)

array([[                 270,                  270,                  270,
        ..., -9223372036854775808, -9223372036854775808,
        -9223372036854775808],
       [                 261,                  185,                   30,
        ..., -9223372036854775808, -9223372036854775808,
        -9223372036854775808],
       [                 313,                  254,                  254,
        ..., -9223372036854775808, -9223372036854775808,
        -9223372036854775808],
       ...,
       [                 747,                   36,                  317,
        ..., -9223372036854775808, -9223372036854775808,
        -9223372036854775808],
       [                 182,                  148,                   85,
        ..., -9223372036854775808, -9223372036854775808,
        -9223372036854775808],
       [                 391,                  179,                  196,
        ..., -9223372036854775808, -9223372036854775808,
        -9223372036854775808]], shape=(100, 999

In [7]:
small_M[:,1]

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 626 stored elements and shape (17771, 1)>

In [45]:
6*100/60

10.0

In [ ]:
def LSH():
    pass
# Devide Matrix into b bands and r rows
# implement hash table to check for identity in linear time

        


_IncompleteInputError: incomplete input (2385955972.py, line 3)

In [13]:
index = np.arange(np.shape(small_M)[0])
print(index)
np.random.shuffle(index)
print(small_M[index, :])

[    0     1     2 ... 17768 17769 17770]
<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 628113 stored elements and shape (17771, 1000)>
  Coords	Values
  (0, 550)	1.0
  (0, 781)	1.0
  (2, 95)	1.0
  (2, 173)	1.0
  (2, 207)	1.0
  (2, 469)	1.0
  (2, 795)	1.0
  (2, 895)	1.0
  (3, 103)	1.0
  (3, 352)	1.0
  (3, 628)	1.0
  (4, 299)	1.0
  (4, 673)	1.0
  (4, 755)	1.0
  (4, 836)	1.0
  (5, 110)	1.0
  (5, 166)	1.0
  (5, 207)	1.0
  (5, 526)	1.0
  (5, 779)	1.0
  (6, 204)	1.0
  (6, 327)	1.0
  (6, 556)	1.0
  (6, 783)	1.0
  (6, 996)	1.0
  :	:
  (17764, 985)	1.0
  (17764, 986)	1.0
  (17764, 991)	1.0
  (17764, 998)	1.0
  (17767, 81)	1.0
  (17767, 118)	1.0
  (17767, 130)	1.0
  (17767, 148)	1.0
  (17767, 180)	1.0
  (17767, 244)	1.0
  (17767, 269)	1.0
  (17767, 385)	1.0
  (17767, 500)	1.0
  (17767, 597)	1.0
  (17767, 628)	1.0
  (17767, 855)	1.0
  (17767, 867)	1.0
  (17767, 912)	1.0
  (17767, 960)	1.0
  (17769, 106)	1.0
  (17769, 200)	1.0
  (17769, 301)	1.0
  (17769, 693)	1.0
  (17769, 793)	1

In [14]:
index

array([15050,  6862,  7205, ...,  4307,  3482,  6790], shape=(17771,))

array([    0,     1,     2, ..., 17768, 17769, 17770], shape=(17771,))