In [100]:
import numpy as np
import scipy.sparse as sparse
import random
import hashlib

# Load in Data

In [2]:
data = np.load('Data/user_movie_rating.npy')[:,0:2]

(65225506, 2)

In [228]:
col = data[:, 0]
row = data[:, 1]

n_col = col.max() + 1
n_row = row.max() + 1 

M = sparse.coo_matrix((np.ones(len(data)), (row, col)), shape=(n_row, n_col)).tocsr()
small_M  = M[:,0:1000]

In [248]:
perm = 100 
perm_seeds = []
row_len,_ = small_M.get_shape()
seed = 100000
for i in range(perm):
    perm_seeds.append(int(hashlib.sha256(str(seed+i).encode()).hexdigest(),16)%4294967295)


In [249]:
import sklearn
_, cols = small_M.shape

signature = []
for i in range(1,cols):
    col = small_M[:,i]
    col_signature = []
    for seed in perm_seeds:


KeyboardInterrupt: 

In [246]:
small_M[:,1]

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 626 stored elements and shape (17771, 1)>

In [ ]:
def LSH():
    pass
# Devide Matrix into b bands and r rows
# implement hash table to check for identity in linear time

        


_IncompleteInputError: incomplete input (2385955972.py, line 3)

In [256]:
index = np.arange(np.shape(small_M)[0])
print(index)
np.random.shuffle(index)
small_M[index, :]

[    0     1     2 ... 17768 17769 17770]


<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 628113 stored elements and shape (17771, 1000)>

array([ 2496,  8580,  2962, ...,  5863, 10298, 13750], shape=(17771,))

array([    0,     1,     2, ..., 17768, 17769, 17770], shape=(17771,))